# Generated by Django 4.0.2 on 2022-03-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_session',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='app_session',
            name='session_data',
        ),
    ]
